# How to Define Collected Metrics

Rating rules assign a value to the consumption of computing resources. By default, a set of metrics is exposed to the Rating service (CloudKitty). Use a custom metrics.yaml file to define the specific metrics that CloudKitty processes for your deployment.

== Step-by-Step to Define Collected Metrics

In a nutshell, the process to define collected metrics involves the following steps:

1. Copy the default metrics.yaml configuration file
2. Retrieve a list of the available metrics that can be configured
3. Define how each metric is collected
4. (Optional) Convert associated units
5. (Optional) Rate different aspects of the same resource
6. Create the Secret CR for the Rating service with the custom configuration files
7. Update the OpenStackControlPlane CR to reference the custom configuration Secret
8. Verify that the custom configuration is applied

Let's see what each step involves in more detail.

=== 1. Copy the default metrics.yaml configuration file

The default `metrics.yaml` file is located in the `cloudkitty-proc` pod. You can copy it to your local machine for editing using the following command:

[source,bash]
----
oc rsh -n openstack cloudkitty-proc-0 cat /etc/cloudkitty/metrics.yaml > metrics.yaml
----

=== 2. Retrieve a list of the available metrics that can be configured

To see the list of available metrics that can be configured in the `metrics.yaml` file, you can use the OpenStack CLI to list the metrics that are currently being collected in your RHOSO deployment. This can be done with the following command:

[source,bash]
----
oc rsh -n openstack openstackclient  list
----

=== 3. Define how each metric is collected

In the `metrics.yaml` file, you can define how each metric is collected by specifying the metric name, the unit of measurement, and any additional arguments that are required for collecting the metric. The format for defining a metric in the `metrics.yaml` file is as follows:

[source,yaml]
----
metrics:
  <metric_name>:
    unit: <unit_indicator>
    alt_name: <alternative_name>
    description: <metric_description>
    groupby:
      - <groupby_attribute>
      - <groupby_attribute>
      ...
      - <groupby_attribute>
    metadata:
      - <metadata_attribute>
    factor: <unit_conversion_factor>
    offset: <unit_conversion_offset>
    mutate: <unit_mutation>
    extra_args:
      - <list_of_optional_arguments>
----

`<metric_name>`:: 
The name of the metric to collect, for example, `ceilometer_cpu`.

`unit`:: 
A string that indicates the unit in which the metric is stored after conversion. This string is for information only, it has no impact on the metric conversion or rating. For example, the unit could be set to `GiB` for the metric `ceilometer_disk_root_size`.

`groupby`:: 
A list of attribute names by which the metrics are grouped on collection, for example, project ID or user ID.

`metadata`:: 
A list of additional attribute names that are collected for the given metric, that the metrics are not to be grouped on. For example, the `type` attribute for the `ceilometer_disk_root_size` metric.

`factor`:: 
An optional factor to use in calculating the conversion rate for the unit quantity. The default factor is `1`.

`offset`:: 
An optional offset to use in calculating the conversion rate for the unit quantity. The default offset is `0`.

`mutate`:: 
An optional operation to apply to the unit quantity after the conversion rate is calculated:
+
*NONE*::: This is the default. The collected data is not modified.
*CEIL*::: The quantity is rounded up to the closest integer.
*FLOOR*::: The quantity is rounded down to the closest integer.
*NUMBOOL*::: If the collected quantity equals 0, it remains at 0, otherwise it is set to 1.
*NOTNUMBOOL*::: If the collected quantity equals 0, set it to 1, otherwise set it to 0.
*MAP*::: Map arbitrary values to new values as defined through the `mutate_map` option. If the value is not found in `mutate_map`, set it to 0. If `mutate_map` is not defined or is empty, all values are set to 0.

`alt_name`:: 
An optional string to use as the display name for the metric instead of the metric name in summary reports.

`description`:: 
An optional field for providing details about the configured rating type.

`extra_args`:: 
An optional list of arguments to apply to the rating:
+
`aggregation_method`::: Defaults to `max`. The aggregation method to use when retrieving measures from Prometheus. Must be one of `avg`, `min`, `max`, `sum`, `count`, `stddev`, `stdvar`.
`query_function`::: The function to apply to an instant vector after the `aggregation_method` or `range_function` has altered the data. Must be one of `abs`, `ceil`, `exp`, `floor`, `ln`, `log2`, `log10`, `round`, `sqrt`.
`query_prefix`::: An arbitrary prefix to add to the Prometheus query generated by the Rating service, separated by a space.
`query_suffix`::: An arbitrary suffix to add to the Prometheus query generated by the Rating service, separated by a space.
`range_function`::: The function to apply instead of the implicit `{aggregation_method}_over_time`. Must be one of `changes`, `delta`, `deriv`, `idelta`, `irange`, `irate`, `rate`.

The following example defines how the `ceilometer_image_size` metric is collected. It specifies that the metric is collected in `MiB`, grouped by resource, user and project, and that the maximum value of the metric is used when retrieving measures.

[source,yaml]
----
metrics:
  ceilometer_image_size:
    unit: MiB
    groupby:
      - resource
      - user
      - project
    metadata:
      - container_format
      - disk_format
    extra_args:
      aggregation_method: max
----

And the next example defines how the `ceilometer_power_status` metric is collected, with a mutation to map the different status values to a binary value indicating whether the instance is on or not:

[source,yaml]
----
metrics:
  ceilometer_power_status:
    unit: instance
    mutate: MAP
    mutate_map:
      1: 1.0 # RUNNING
      2: 0.0 # BLOCKED
      3: 0.0 # PAUSED
      4: 0.0 # SHUTDOWN
      5: 0.0 # SHUTOFF
      6: 0.0 # CRASHED
    groupby:
      - id
----

=== 4. (Optional) Convert associated units

If you need to convert the collected quantity from one unit to another, for example, from MiB to GiB, configure the factor and offset options. The factor and offset options are used to calculate the final collected quantity with the following formula:

quantity = collected_quantity * factor + offset.

For example, to convert the `ceilometer_image_size` metric from B to MiB, you can set the factor to `1/1048576` (which is 1/1024 * 1024) and the offset to `0`:

[source,yaml]
----
metrics:
  ceilometer_image_size:
    unit: MiB
    factor: 1/1048576 # Dividing by 1024 * 1024 to convert from B to MiB
    offset: 0
----

=== 5. (Optional) Rate different aspects of the same resource

To rate different aspects of the same resource type that is collected through the same metric, you can add additional rating types to a single metric. For example, to rate the use of both the flavor and the used CPU time by an instance, define two units for the `ceilometer_cpu` metric:

[source,yaml]
----
  ceilometer_cpu:
    - unit: instance
      alt_name: flavor
      groupby:
        - resource
        - user
        - project
      metadata:
        - flavor_name
        - flavor_id
      mutate: NUMBOOL
      extra_args:
        aggregation_method: max
    - unit: ns
      alt_name: cpu_time
      groupby:
        - resource
        - user
        - project
      mutate: NUMBOOL
      extra_args:
        aggregation_method: max
----

=== 6. Create the Secret CR for the Rating service with the custom configuration files

After defining the collected metrics in the `metrics.yaml` file, you need to create a `Secret` CR in OpenShift to store the custom configuration file. This `Secret` will be referenced in the `OpenStackControlPlane` CR to apply the custom configuration to the Rating service (CloudKitty).

[source,bash]
----
oc create secret generic cloudkitty_secret \
 --from-file metrics.yaml -n openstack
----

Verify that the `Secret` has been created successfully:

[source,bash]
----
oc describe secret cloudkitty_secret -n openstack
----

=== 7. Update the OpenStackControlPlane CR to reference the custom configuration Secret

Finally, you need to update the `OpenStackControlPlane` CR to reference the `Secret` that contains your custom `metrics.yaml` file. This will ensure that the Rating service (CloudKitty) uses your custom configuration for collecting metrics.

[source,bash]
----
oc edit OpenStackControlPlane -n openstack
----

Add the following configuration in the telemetry section of the `OpenStackControlPlane` CR to reference the custom `metrics.yaml` file:

[source,yaml]
----
spec:
  telemetry:
    template:
      ...
      cloudkitty:
        cloudKittyAPI:
          customConfigsSecretName: cloudkitty_secret
        cloudKittyProc:
          customConfigsSecretName: cloudkitty_secret
----

[WARNING]
Always back up your CR definition before making any modifications. Incorrect changes can disrupt your Telemetry services and impact the stability of your RHOSO environment.

After saving the modified OpenStackControlPlane CR YAML, the Telemetry Operator will detect this change and initiate the reconciliation process, applying your custom configuration to `cloudkitty`. Monitor the `cloudkitty` pods to ensure they restart successfully and apply the new configuration.

=== 8. Verify that the custom configuration is applied

To verify that your custom `metrics.yaml` configuration is applied correctly, you inspect the new metrics.yaml file in the `cloudkitty-proc` pod and check that it reflects the changes you made.

[source,bash]
----
oc rsh -n openstack cloudkitty-proc-0 cat /etc/cloudkitty/metrics.yaml
----